### PR TITLE
Upgrade to bevy 0.12

### PR DESCRIPTION
**Pull request by crillon**
Updated the `bevy` and `bevy_egui` dependencies.
Also fixed several typos and #7.

All tests are green. Examples also work :)

### CODE REVIEW

**Comment by crillon** [comment]
Oh, I forget, I'm not sure how to handle the new `AssetEvent::LoadedWithDependencies` event. At the moment it's being handled the same way as the `Added` and `Modified` events. Any thoughts on this?

<details>
<summary>Details</summary>

```rust
    let mut changed = HashSet::default();
    let mut removed = Vec::new();
    for event in shader_events.read() {
        match event {
            AssetEvent::Added { id }
            | AssetEvent::Modified { id }
            | AssetEvent::LoadedWithDependencies { id } => {
                changed.insert(id.clone());
            }
            AssetEvent::Removed { id } => {
                changed.remove(id);
                removed.push(id.clone());
            }
        }
    }
```
https://github.com/Zheoni/bevy_pixel_buffer/pull/8/commits/0884571fed6d53445691832ef3269177dcade4a0#diff-31a275d3425f4b01b1b738927e79db292fc85fdde740a246db7d41bc515ed59cR244-R256

```rust
    // Update image bind group cache
    let mut invalid = HashSet::default();
    for event in image_events.read() {
        match event {
            AssetEvent::Added { id }
            | AssetEvent::Modified { id }
            | AssetEvent::Removed { id }
            | AssetEvent::LoadedWithDependencies { id }
                if buffer_images.contains(id) =>
            {
                invalid.insert(id.clone());
            }
            _ => {}
        }
    }
```
https://github.com/Zheoni/bevy_pixel_buffer/pull/8/commits/0884571fed6d53445691832ef3269177dcade4a0#diff-31a275d3425f4b01b1b738927e79db292fc85fdde740a246db7d41bc515ed59cL265-R281
</details>

**Comment by Zheoni** [comment]
Thank you so much! I did not have time to update to this release. About the new asset event, I honestly don't know either. We can leave it like this and hope it's the correct decision 😅 

I also have a question. What GPU do you have? Since the last update I have swapped my GPU from nvidia to amd, and now I'm getting this error printed every frame, everything works though. It also prints in the old version, so it's not your update.

image

**Comment by Zheoni** [comment]
Opened an issue for this #9

**Comment by crillon** [comment]
I have an Nvidia GPU, have no idea what the problem might be :(
Maybe you should create a new issue in the bevy repo

**Pull request merged**
